name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleRelease
    - name: diagnosing
      run: |
        find ./app/build/outputs/apk/
        echo "${{ secrets.KEYSTORE_B64 }}" > keystore.b64
        base64 --decode keystore.b64 > keystore.jks
        echo "RELEASE_STORE_FILE_PATH=../keystore.jks" > local.properties
        echo "RELEASE_STORE_PASSWORD=${{ secrets.KEYSTORE_PW }}" >> local.properties
        echo "RELEASE_STORE_KEY_PASS=${{ secrets.KEYSTORE_KEY_PW }}" >> local.properties
        echo "RELEASE_STORE_KEY_ALIAS=${{  secrets.KEYSTORE_KEY_ALIAS }}" >> local.properties
    - name: Releasing
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "Build"
        files: |
          ./app/build/outputs/apk/release/app-release-unsigned.apk
