name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Setup sign key data
      run: |
        echo "${{ secrets.KEYSTORE_B64 }}" > keystore.b64
        base64 --decode keystore.b64 > keystore.jks
        echo "RELEASE_STORE_FILE_PATH=../keystore.jks" > local.properties
        echo "RELEASE_STORE_PASSWORD=${{ secrets.KEYSTORE_PW }}" >> local.properties
        echo "RELEASE_STORE_KEY_PASS=${{ secrets.KEYSTORE_KEY_PW }}" >> local.properties
        echo "RELEASE_STORE_KEY_ALIAS=${{ secrets.KEYSTORE_KEY_ALIAS }}" >> local.properties
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleRelease

    - name: Releasing
      if: ${{ success() }}
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "v0.${{ github.run_number }}"
        prerelease: false
        title: "Signed .APK [${{ github.sha }}]"
        files: |
          ./app/build/outputs/apk/release/app-release.apk
